server:
  servlet:
    context-path: /demo
    port: 8081
spring:
  datasource:
    name: demo
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
